// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJZ9gEzX-tegT5bYBMhQ6WB3KuoWRyxI',
    appId: '1:536587697190:web:257be96c3a39e9117f3ae7',
    messagingSenderId: '536587697190',
    projectId: 'fashai-80d35',
    authDomain: 'fashai-80d35.firebaseapp.com',
    storageBucket: 'fashai-80d35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwa-GatuXrtsRM7gZozKNuJjNAI-zKE8o',
    appId: '1:536587697190:android:ca38d1da6d33bd797f3ae7',
    messagingSenderId: '536587697190',
    projectId: 'fashai-80d35',
    storageBucket: 'fashai-80d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwOYwAWGb6b9Xpc04RbmxVBbmXkoIaRE',
    appId: '1:536587697190:ios:12567c3a953cc19a7f3ae7',
    messagingSenderId: '536587697190',
    projectId: 'fashai-80d35',
    storageBucket: 'fashai-80d35.firebasestorage.app',
    iosBundleId: 'com.example.fashai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNwOYwAWGb6b9Xpc04RbmxVBbmXkoIaRE',
    appId: '1:536587697190:ios:12567c3a953cc19a7f3ae7',
    messagingSenderId: '536587697190',
    projectId: 'fashai-80d35',
    storageBucket: 'fashai-80d35.firebasestorage.app',
    iosBundleId: 'com.example.fashai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeJZ9gEzX-tegT5bYBMhQ6WB3KuoWRyxI',
    appId: '1:536587697190:web:c0e2204335f658327f3ae7',
    messagingSenderId: '536587697190',
    projectId: 'fashai-80d35',
    authDomain: 'fashai-80d35.firebaseapp.com',
    storageBucket: 'fashai-80d35.firebasestorage.app',
  );

}